MyWallet/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as drf_views

from MyWallet import api
from MyWallet.rest import views as rest_views
from MyWallet.views import budgets as budget_views
from MyWallet.views import categories as category_views
from MyWallet.views import index as general_views
from MyWallet.views import transactions as transaction_views
from MyWallet.views import recurrences as recurrence_views


router = routers.DefaultRouter()
router.register(r'accounts', rest_views.AccountViewSet)
router.register(r'transactions', rest_views.TransactionViewSet)
router.register(r'categories', rest_views.CategoryViewSet)
router.register(r'recurrences', rest_views.RecurringTransactionsViewset)

urlpatterns = [
    path('', general_views.IndexView.as_view(), name='index'),
    path('profile/', general_views.ProfileView.as_view(), name='profile'),

    path('auth/', include('allauth.urls')),

    path('transactions/', transaction_views.TransactionIndex.as_view(), name='transactions'),
    path('transactions/<int:pk>/',
         transaction_views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/update/',
         transaction_views.TransactionUpdateView.as_view(), name='transaction_update'),
    path('transactions/<int:pk>/delete/',
         transaction_views.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('transactions/create/transfer/',
         transaction_views.TransactionCreate.as_view(), {'type': 'transfer'}, name='transfer_new'),
    path('transactions/create/withdraw/',
         transaction_views.TransactionCreate.as_view(), {'type': 'withdraw'}, name='withdraw_new'),
    path('transactions/create/deposit/',
         transaction_views.TransactionCreate.as_view(), {'type': 'deposit'}, name='deposit_new'),

path('recurrences/',
         recurrence_views.RecurringTransactionIndex.as_view(), name='recurrences'),
    path('recurrences/create/',
         recurrence_views.RecurrenceCreateView.as_view(), name='recurrence_create'),
    path('recurrences/disabled/',
         recurrence_views.DisabledRecurrencesView.as_view(), name='disabled_recurrences'),
    path('recurrences/<int:pk>/', recurrence_views.RecurrenceDetailView.as_view(),
         name='recurrence_detail'),
    path('recurrences/<int:pk>/update/', recurrence_views.RecurrenceUpdateView.as_view(),
         name='recurrence_update'),
    path('recurrences/<int:pk>/delete/', recurrence_views.RecurrenceDeleteView.as_view(),
         name='recurrence_delete'),
    path('recurrences/<int:pk>/transaction/create/',
         recurrence_views.RecurrenceTransactionCreateView.as_view(),
         name='recurrence_transaction_create'),

    path('categories/', category_views.CategoryIndex.as_view(), name='categories'),
    path('categories/month/', category_views.CategoryByMonth.as_view(), name='category_by_month'),
    path('categories/inactive/', category_views.InactiveCategoriesView.as_view(),
         name='inactive_categories'),
    path('categories/month/<int:year>/<int:month>/', category_views.CategoryByMonth.as_view(),
         name='categories_month'),
    path('categories/assign/',
         category_views.assign_categories, name='category_assign'),
    path('categories/create/',
         category_views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/',
         category_views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/<int:year>/<int:month>/',
         category_views.CategoryDetailView.as_view(), name='category_month'),
    path('categories/<int:pk>/delete/', category_views.CategoryDeleteView.as_view(),
         name='category_delete'),
    path('categories/<int:pk>/update/', category_views.CategoryUpdateView.as_view(),
         name='category_update'),

    path('budgets/', budget_views.BudgetIndex.as_view(), name='budgets'),
    path('budgets/<int:year>/<int:month>/',
         budget_views.BudgetIndex.as_view(), name='budget_month'),


    path('api/accounts/<account_type>/', api.get_accounts, name='api_accounts'),
    path('api/balance/<dstart>/<dend>/', api.get_balances, name='api_balance'),
    path('api/account/<int:account_id>/balance/<dstart>/<dend>/',
         api.get_account_balance, name='api_account_balance'),
    path('api/accounts_balance/<dstart>/<dend>/',
         api.get_accounts_balance, name='api_accounts_balance'),
    path('api/category_spending/<dstart>/<dend>/',
         api.category_spending, name='category_spending'),
    path('api/update_current_recurrences/',
         recurrence_views.ReccurrenceSetNextOccurence.as_view(),
         name='update_current_recurrences'),


    path('manifest.json', TemplateView.as_view(template_name='MyWallet/manifest.json'),
         name='manifest'),

    path('rest/account_names', rest_views.AccountNameView.as_view()),
    path('rest/recurrence_names', rest_views.RecurrenceNameView.as_view()),
    path('rest/accounts/personal', rest_views.PersonalAccountsView.as_view()),
    path('rest/accounts/foreign', rest_views.ForeignAccountsView.as_view()),
    path('rest/', include(router.urls)),
    path('api-token-auth/', drf_views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyWallet.urls')),
]

MyWallet/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from MyWallet import models


class AccountCreateForm(forms.ModelForm):
    class Meta:
        model = models.Account
        fields = ['name', 'initial_balance', 'active', 'show_on_dashboard']

    initial_balance = forms.DecimalField(max_digits=10, decimal_places=2, initial=0)

    def clean_name(self):
        name = self.cleaned_data['name']
        if models.Account.objects.filter(name=name, account_type=models.Account.PERSONAL).exists():
            raise ValidationError(_('An account with this name already exists'))
        return name

    def save(self, commit=True):
        account = super(AccountCreateForm, self).save(commit)
        if self.cleaned_data['initial_balance']:
            account.set_initial_balance(self.cleaned_data['initial_balance'])
        return account


class BudgetForm(forms.Form):
    budget_id = forms.IntegerField()
    category_id = forms.IntegerField()
    category_name = forms.CharField(max_length=64)
    spent = forms.CharField(max_length=32)
    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0)
    left = forms.CharField(max_length=32)
    month = forms.DateField()

    def save(self):
        if self.cleaned_data['budget_id'] == -1:
            if self.cleaned_data['amount'] != 0:
                # new budget
                models.Budget.objects.create(
                    category_id=self.cleaned_data['category_id'],
                    month=self.cleaned_data['month'],
                    amount=self.cleaned_data['amount'])
        elif self.cleaned_data['amount'] != 0:
            models.Budget.objects.update_or_create(id=self.cleaned_data['budget_id'], defaults={
                'amount': self.cleaned_data['amount']
            })
        else:
            models.Budget.objects.get(id=self.cleaned_data['budget_id']).delete()


BudgetFormSet = forms.formset_factory(BudgetForm, extra=0)


class TransactionForm(forms.ModelForm):
    class Meta:
        model = models.Transaction
        fields = ['title', 'source_account', 'destination_account',
                  'amount', 'date', 'value_date', 'category', 'notes']

    amount = forms.DecimalField(max_digits=10, decimal_places=2, min_value=0.01)
    category = forms.ModelChoiceField(
        queryset=models.Category.objects.exclude(active=False).order_by('name'), required=False)
    value_date = forms.DateField(required=False)

    source_account = forms.ModelChoiceField(queryset=models.Account.objects.filter(
        account_type=models.Account.PERSONAL, active=True))
    destination_account = forms.ModelChoiceField(queryset=models.Account.objects.filter(
        account_type=models.Account.PERSONAL, active=True))

    def save(self, commit=True):
        transaction = super().save(commit)
        src = self.cleaned_data['source_account']
        dst = self.cleaned_data['destination_account']
        amount = self.cleaned_data['amount']
        value_date = self.cleaned_data.get('value_date') or transaction.date
        models.Split.objects.update_or_create(
            transaction=transaction, amount__lt=0,
            defaults={'amount': -amount, 'account': src,
                      'opposing_account': dst, 'date': value_date,
                      'title': transaction.title,
                      'category': self.cleaned_data['category']})
        models.Split.objects.update_or_create(
            transaction=transaction, amount__gt=0,
            defaults={'amount': amount, 'account': dst,
                      'opposing_account': src, 'date': value_date,
                      'title': transaction.title,
                      'category': self.cleaned_data['category']})
        return transaction


class TransferForm(TransactionForm):
    def save(self, commit=True):
        transaction = super().save(commit)
        src = self.cleaned_data['source_account']
        dst = self.cleaned_data['destination_account']
        amount = self.cleaned_data['amount']
        models.Split.objects.update_or_create(
            transaction=transaction, amount__lt=0,
            defaults={'amount': -amount, 'account': src,
                      'opposing_account': dst, 'date': transaction.date,
                      'title': transaction.title,
                      'category': self.cleaned_data['category']})
        models.Split.objects.update_or_create(
            transaction=transaction, amount__gt=0,
            defaults={'amount': amount, 'account': dst,
                      'opposing_account': src, 'date': transaction.date,
                      'title': transaction.title,
                      'category': self.cleaned_data['category']})
        return transaction

    def clean(self):
        super().clean()
        self.instance.transaction_type = models.Transaction.TRANSFER
        if self.cleaned_data['source_account'] == self.cleaned_data['destination_account']:
            error = 'source and destination account have to be different'
            self.add_error('destination_account', error)
            self.add_error('source_account', error)


class WithdrawForm(TransactionForm):
    destination_account = forms.CharField(max_length=64, label=_('Debitor'),
                                          widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def save(self, commit=True):
        account, _ = models.Account.objects.get_or_create(
            name=self.cleaned_data['destination_account'],
            account_type=models.Account.PERSONAL)
        self.cleaned_data['destination_account'] = account
        return super().save(commit)

    def clean(self):
        super().clean()
        self.instance.transaction_type = models.Transaction.WITHDRAW


class DepositForm(TransactionForm):
    source_account = forms.CharField(max_length=64, label=_('Creditor'),
                                     widget=forms.TextInput(attrs={'autocomplete': 'off'}))

    def save(self, commit=True):
        account, _ = models.Account.objects.get_or_create(name=self.cleaned_data['source_account'],
                                                          account_type=models.Account.PERSONAL)
        self.cleaned_data['source_account'] = account
        return super().save(commit)

    def clean(self):
        super().clean()
        self.instance.transaction_type = models.Transaction.DEPOSIT


class RecurringTransactionForm(forms.ModelForm):
    class Meta:
        model = models.RecurringTransaction
        fields = ['title', 'date', 'amount', 'src', 'dst', 'category',
                  'interval', 'multiplier', 'weekend_handling', 'usual_month_day']

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if amount < 0:
            raise forms.ValidationError(_('Amount has to be positive'))
        return amount

    def clean(self):
        super(RecurringTransactionForm, self).clean()
        src = self.cleaned_data['src']
        dst = self.cleaned_data['dst']
        if src.account_type == models.Account.PERSONAL:
            if dst.account_type == models.Account.PERSONAL:
                self.transaction_type = models.Transaction.TRANSFER
            else:
                self.transaction_type = models.Transaction.WITHDRAW
        elif dst.account_type == models.Account.PERSONAL:
            self.transaction_type = models.Transaction.DEPOSIT
        else:
            raise forms.ValidationError(
                _('You are trying to create a transaction between two foreign accounts'))

    def save(self, commit=False):
        recurrence = super(RecurringTransactionForm, self).save(commit=False)
        recurrence.transaction_type = self.transaction_type
        recurrence.save()
        return recurrence


class ReconcilationForm(forms.ModelForm):
    class Meta:
        model = models.Transaction
        fields = ['title', 'balance', 'notes']

    balance = forms.DecimalField(max_digits=10, decimal_places=2, required=True,
                                 label=_('Actual balance'))

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super(ReconcilationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        transaction = super().save(False)
        transaction.transaction_type = models.Transaction.SYSTEM
        transaction.save()
        src = models.Account.objects.get(account_type=models.Account.SYSTEM).pk
        dst = models.Account.objects.get(pk=self.account)
        balance = self.cleaned_data['balance']
        amount = balance - dst.balance
        models.Split.objects.create(transaction=transaction, amount=-amount,
                                    account_id=src, opposing_account=dst, title=transaction.title)
        models.Split.objects.create(transaction=transaction, amount=amount,
                                    account=dst, opposing_account_id=src, title=transaction.title)
        return transaction

    def clean(self):
        super().clean()
        if self.cleaned_data['balance'] == models.Account.objects.get(pk=self.account).balance:
            self.add_error('balance', 'You provided the same balance!')


class SplitForm(forms.ModelForm):
    class Meta:
        model = models.Split
        fields = ['title', 'account', 'opposing_account', 'date', 'amount', 'category']
    account = forms.ModelChoiceField(queryset=models.Account.objects.exclude(
        account_type=models.Account.SYSTEM))
    opposing_account = forms.ModelChoiceField(queryset=models.Account.objects.exclude(
        account_type=models.Account.SYSTEM))


TransactionFormSet = forms.models.inlineformset_factory(
    models.Transaction, models.Split, form=SplitForm, extra=1
    )


class ExportForm(forms.Form):
    start = forms.DateField()
    end = forms.DateField()
    accounts = forms.ModelMultipleChoiceField(
        queryset=models.Account.objects.personal())

MyWallet/templates/MyWallet/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" sizes="192x192" href="{% static 'MyWallet/img/android-chrome-192x192.png' %}">
    <link rel="icon" sizes="512x412" href="{% static 'MyWallet/img/android-chrome-512x512.png' %}">
    <link rel="shortcut icon" type="image/x-icon" sizes="32x32" href="{% static 'MyWallet/img/favicon-32x32.png' %}" />
    <link rel="shortcut icon" type="image/x-icon" sizes="16x16" href="{% static 'MyWallet/img/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% url 'manifest' %}">
    {% block stylesheets %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'MyWallet/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/skin-blue-light.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <title>MyWallet</title>
  </head>
  <body class="hold-transition skin-blue-light sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>AgS</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>My</b>Wallet</span>
        </a>
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only"> Toggle navigation </span>
          </a>

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> New </a>
              <ul class="dropdown-menu">
                <li class="header">
                  <a href="{% url 'withdraw_new' %}"> New Withdrawal </a>
                </li>
                <li>
                  <a href="{% url 'deposit_new' %}"> New Deposit </a>
                </li>
                <li>
                  <a href="{% url 'transfer_new' %}"> New Transfer</a>
                </li>
              </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <aside class="main-sidebar">
        <section class="sidebar">
          <ul class="sidebar-menu" data-widget="tree">
            <li class="header"> MAIN NAVIGATION </li>
            <li {% if menu == "home" %}class="active"{% endif %}>
              <a href="/">
                <i class="fa fa-home"></i> <span> Витрати та доходи </span>
              </a>
            </li>
            <li{% if menu == "recurrences" %} class="active"{% endif %}>
              <a href="{% url 'recurrences' %}"><i class="fa fa-repeat"></i>
                <span> Платежі</span>
              </a>
            </li>
            <li{% if menu == "categories" %} class="active"{% endif%}>
              <a href="{% url 'category_by_month' %}">
                <i class="fa fa-tags" aria-hidden="true"></i>
                <span> Статистика </span>
              </a>
            </li>
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">
          <div class="flash-message">
              {% for message in messages %}
              <div class="alert alert-dismissable">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              </div>
              {% endfor %}
          </div>
        <section class="content-header">
          {% block content_header %}
          {% endblock %}
        </section>
        <section class="content">
          {% block content %}
          {% endblock %}
        </section>
      </div>
      <footer class="main-footer">
        <strong>MyWallet</strong>
      </footer>
    </div>
    <script src="{% static 'MyWallet/js/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/adminlte.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
            window.setTimeout(function() {
                $(".flash-message").fadeTo(500, 0).slideUp(500, function(){
                    $(this).remove();
                });
            }, 4000);
        })
    </script>
  </body>
</html>

MyWallet/templates/MyWallet/budget_index.html
{% extends 'MyWallet/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}

{% block content_header %}
<h1>{% trans 'Budgets' %}</h1>
<ol class="breadcrumb">
  <li><a href="/">{% trans 'Home' %}</a></li>
  <li class="active">{% trans 'Budgets' %}</li>
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-body">
    <div class="text-center">
      <a href="{% url 'budget_month' previous_month.year previous_month.month %}" class="btn btn-xs btn-default">{% trans 'Previous' %}</a>
      <span>{{ month|date:'F Y'}}</span>
      <a href="{% url 'budget_month' next_month.year next_month.month %}" class="btn btn-xs btn-default">{% trans 'Next' %}</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h4>{% trans 'Allocated' %}</h4>
        <h3>{{ allocated }}</h3>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="small-box bg-red">
      <div class="inner">
        <h4>{% trans 'Spent' %}</h4>
        <h3>{{ spent }}</h3>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="small-box bg-green">
      <div class="inner">
        <h4>{% trans 'Left to spend' %}</h4>
        <h3>{{ left }}</h3>
      </div>
    </div>
  </div>
</div>
<div class="box">
  <form method="post">
    {% csrf_token %}
    {{ form.management_form }}
  <div class="box-header with-border">
    <h3 class="box-title">{% blocktrans with month_str=month|date:'F Y' %}Budget for {{ month_str }}{% endblocktrans %}</h3>
  </div>
  <div class="box-body no-padding">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-md-6">{% trans 'Name' %}</th>
          <th class="col-md-2">{% trans 'Allocated' %}</th>
          <th class="col-md-2">{% trans 'Money spent' %}</th>
          <th class="col-md-2">{% trans 'Left' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for form in form %}
        {{ form.category_id.as_hidden }}
        {{ form.month.as_hidden }}
        {{ form.budget_id.as_hidden }}
        {{ form.category_name.as_hidden }}
        {{ form.spent.as_hidden }}
        {{ form.left.as_hidden }}
        <tr>
          <td>
            {{ form.category_name.value }}
            {{ form.errors }}
          </td>
          <td>
              {{ form.amount|add_class:"form-control" }}
          </td>
          <td>{{ form.spent.value|intcomma }}</td>
          <td>{{ form.left.value|intcomma }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="box-footer">
    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
  </div>
  </form>
</div>
{% endblock %}

MyWallet/templates/MyWallet/transaction_edit.html
{% extends 'MyWallet/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Transactions
  <small>
    {% if object %}
    {% blocktrans with object_name=object.title %}Edit {{ object.title }}{% endblocktrans %}
    {% else %}
    {% blocktrans %}Add new {{ submenu }}{% endblocktrans %}
    {% endif %}
  </small>
</h1>
<ol class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="{% url 'transactions' %}">{% trans 'Transactions' %}</a></li>
  {% if object %}
  <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="active">{% trans 'Edit' %}</li>
  {% else %}
  <li class="active">{% trans 'Create' %}</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
  <h3 class="box-title">{% trans 'Transaction Details' %}</h3>
</div>
<div class="box-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      <div class="form-group{% if form.title.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
        <div class="col-sm-8">
          {{ form.title|add_class:"form-control" }}
          {% for error in form.title.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.source_account.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.source_account.id_for_label }}">{{ form.source_account.label }}</label>
        <div class="col-sm-8">
          {{ form.source_account|add_class:"form-control" }}
          {% for error in form.source_account.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.destination_account.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.destination_account.id_for_label }}">{{ form.destination_account.label }}</label>
        <div class="col-sm-8">
          {{ form.destination_account|add_class:"form-control" }}
          {% for error in form.destination_account.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.amount.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.amount.id_for_label }}">{{ form.amount.label }}</label>
        <div class="col-sm-8">
          {{ form.amount|add_class:"form-control" }}
          {% for error in form.amount.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.date.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
        <div class="col-sm-8">
          {{ form.date|add_class:"form-control date-input" }}
          {% for error in form.date.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.value_date.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.value_date.id_for_label }}">{{ form.value_date.label }}</label>
        <div class="col-sm-8">
          {{ form.value_date|add_class:"form-control date-input" }}
          {% for error in form.value_date.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.category.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
        <div class="col-sm-8">
          {{ form.category|add_class:"form-control" }}
          {% for error in form.category.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <div class="form-group{% if form.notes.errors %} has-error{% endif %}">
        <label class="col-sm-2 control-label" for="{{ form.notes.id_for_label }}">{{ form.notes.label }}</label>
        <div class="col-sm-8">
          {{ form.notes|add_class:"form-control" }}
          {% for error in form.notes.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
    </form>
</div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'vendor/js/bootstrap3-typeahead.min.js' %}"></script>

<script>
$(function() {
  $('.date-input').datepicker({
  autoclose: true,
  format: 'yyyy-mm-dd',
  orientation: 'bottom'

  });
  if ($('input#id_source_account').length > 0) {
      $.getJSON('{% url 'api_accounts' 'FOREIGN' %}').done(function (data) {
          $('#id_source_account').typeahead({source: data});
      });
  }
  if ($('input#id_destination_account').length > 0) {
      $.getJSON('{% url 'api_accounts' 'FOREIGN' %}').done(function (data) {
          $('#id_destination_account').typeahead({source: data});
      });
  }
  $('.date-input').attr('autocomplete', 'off');
})
</script>
{% endblock %}